version: 2.1
orbs:
  ruby: circleci/ruby@1.0
  coveralls: coveralls/coveralls@1.0.5

defaults: &defaults
  working_directory: ~/log-analyser
  docker:
    - image: cimg/ruby:2.7-node
  executor: ruby/default

restore_gems: &restore_gems
  restore_cache:
    keys:
      - gems-{{ checksum "log-analyser.gemspec" }}-{{ checksum ".travis.yml"}}
      - gems

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_gems
      - run:
          shell: /bin/bash -l
          command: |
            bundle check || bundle install
      - save_cache:
          key: gems-{{ checksum "log-analyser.gemspec" }}-{{ checksum ".travis.yml"}}
          paths:
            - /usr/local/rvm/gems
      - run:
          name: Validate that gemspec is up-to-date
          shell: /bin/bash -l
          command: |
            bundle exec rake build
            export gemspec_changes="$(git diff -- log-analyser.gemspec | egrep '(s\.version|s\.files)')"
            if [ "$gemspec_changes" != "" ]; then
              echo "'bundle exec rake build' caused gemspec changes"
              echo "Please run the command locally and commit the changes."
              echo $gemspec_changes
              exit 1
            fi
  rubocop:
    <<: *defaults
    steps:
      - checkout
      - *restore_gems
      - restore_cache:
          keys:
            - rubocop-v2-parallel-{{ .Branch }}
            - rubocop-v2-parallel-
      - run: bundle install
      - run:
          name: run Rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: rubocop-v2-parallel-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - tmp/rubocop_cache
  rspec:
    <<: *defaults
    steps:
      - checkout
      - *restore_gems
      - run: bundle install
      - run:
          name: run tests
          command: bundle exec rspec
      - coveralls/upload:
          path_to_lcov: ./coverage/lcov/log-analyser.lcov

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - rubocop:
          requires:
            - build
      - rspec:
          requires:
            - build
